version: "3.7"

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: mongodb://mongodb:27017/nuocgpt
      SECRET_KEY: guiyfgc837tgf3iw87-012389764
      OPENAI_API_KEY: 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
      AWS_SECRET_ACCESS_KEY: hIlTGM4U6cDzrm++3snM4RmFhxG1d+5CAxIle0Bo
      AWS_ACCESS_KEY: AKIAYZWP2RCQZIKP4AML
      AWS_S3_BUCKET: nuocgpt-vectorstore
      AWS_REGION: ap-southeast-1
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_USER: long.nguyen@enouvo.com
      SMTP_PASS: knnomsfsyqllxpag
      TWILIO_ACCOUNT_SID: AC3afbb6b9f254002e3e696202378bd77a
      TWILIO_AUTH_TOKEN: 6f67302ed6b2c8f52dc393ed31af58f6
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:7.0.0
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local
