from enum import Enum


class ErrorMessage(str, Enum):
    INCORRECT_EMAIL_OR_PASSWORD = 'INCORRECT_EMAIL_OR_PASSWORD'
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    USER_NOT_VERIFIED = 'USER_NOT_VERIFIED'
    OTP_INCORRECT_OR_EXPIRED = 'OTP_INCORRECT_OR_EXPIRED'
    TOKEN_INVALID_OR_EXPIRED = 'TOKEN_INVALID_OR_EXPIRED'