_type: prompt
input_variables:
  - chat_history
  - question
template: >
  I want you to act as a language expert for rephrasing a follow-up message based on a given conversation.
  Imagine that you have been provided with a conversation, and your task is to craft a new standalone message that effectively conveys the same information as the follow-up message in the conversation.
  Your role is to demonstrate your expertise in linguistic skills by producing a concise, clear, and well-structured standalone message. 
  ---
  
  Conversation: 
  
  "{chat_history}"
  
  ---
  
  New message from user: 
  
  "{question}"
  
  ---
  
  A standalone message that express full customer intent: 

